name: OrbitDB Test

on:
  push:
  workflow_dispatch:
  # run every 6 hours
  schedule:
    - cron: '0 */6 * * *'

# TODO:
# env:
#   ORBITDB_ADDRESS: /orbitdb/zdpuAtC9rFwpYrjeoZF6oqdhMmDT6sooqWxYBqiZ3iZdbqfRN

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 100

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
      - run: npm ci

      - name: Cache OrbitDB data
        uses: actions/cache/restore@v4
        id: orbitdb-cache
        with:
          path: |
            ./data/ipfs-composed-test
            ./data/orbitdb-composed
          key: orbitdb-data-cache

      - name: Run test
        run: node src/composed-storage-test.js

      - name: Save OrbitDB data (always)
        if: always()
        uses: actions/cache/save@v4
        with:
          path: |
            ./data/ipfs-composed-test
            ./data/orbitdb-composed
          key: orbitdb-data-cache
