name: OrbitDB Replication Tests

on:
  push:
  pull_request:
    branches: [ main ]

jobs:
  multi-peer-replication-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - run: bun install
      - name: Start Peer 1
        run: bun run src/peer1.js &
      - name: Wait for Peer 1 to start
        run: sleep 5
      - name: Start Peer 2
        run: bun run src/peer2.js
